export { default as GitHubIcon } from "./GitHubIcon.svelte";
export { default as LinkedInIcon } from "./LinkedInIcon.svelte";
export { default as EmailIcon } from "./EmailIcon.svelte";
export { default as ResumeIcon } from "./ResumeIcon.svelte";
export { default as SunIcon } from "./SunIcon.svelte";
export { default as MoonIcon } from "./MoonIcon.svelte";
export { default as StarIcon } from "./StarIcon.svelte";
export { default as ForkIcon } from "./ForkIcon.svelte";
export { default as ArrowUpRightIcon } from "./ArrowUpRightIcon.svelte";
